name: Trigger auto deployment for container-app-bd5mqx5qefyni

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-bd5mqx5qefyni-AutoDeployTrigger-167c3164-580f-4e32-a74a-31b443f861d5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPBD5MQX5QEFYNI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPBD5MQX5QEFYNI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPBD5MQX5QEFYNI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: containerregistrybd5mqx5qefyni.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPBD5MQX5QEFYNI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPBD5MQX5QEFYNI_REGISTRY_PASSWORD }}
          containerAppName: container-app-bd5mqx5qefyni
          resourceGroup: ehamaitodoa3ca
          imageToBuild: containerregistrybd5mqx5qefyni.azurecr.io/container-app-bd5mqx5qefyni:${{ github.sha }}


