name: Trigger auto deployment for container-app-jmrf6qey24czs

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-jmrf6qey24czs-AutoDeployTrigger-d3589bb1-4a3d-4092-b17c-74eb655b683c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPJMRF6QEY24CZS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPJMRF6QEY24CZS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPJMRF6QEY24CZS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: containerregistryjmrf6qey24czs.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPJMRF6QEY24CZS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPJMRF6QEY24CZS_REGISTRY_PASSWORD }}
          containerAppName: container-app-jmrf6qey24czs
          resourceGroup: ehamaitodo859e
          imageToBuild: containerregistryjmrf6qey24czs.azurecr.io/container-app-jmrf6qey24czs:${{ github.sha }}
          dockerfilePath: Dockerfile


