name: Trigger auto deployment for container-app-v4ae6o5uyz2jc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-v4ae6o5uyz2jc-AutoDeployTrigger-0518184a-c7d1-416b-a747-878245521b22.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPV4AE6O5UYZ2JC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPV4AE6O5UYZ2JC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPV4AE6O5UYZ2JC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPV4AE6O5UYZ2JC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPV4AE6O5UYZ2JC_REGISTRY_PASSWORD }}
          containerAppName: container-app-v4ae6o5uyz2jc
          resourceGroup: ehamaitodo99ed
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


